### ISSUE TITLE
Increase Resources Temporarily During Deployment Time

### ISSUE THREAD

**Issue by Ramrachai** [Ramrachai/indigenous-connect-backend#8]
### **Increase Resources Temporarily During Deployment Time**

**Issue Type:** Feature Request  
**Priority:** Medium  

---

#### **Description**  
We are currently running the *iConnect* application on an AWS EC2 instance with the **t2.micro** instance type. This instance provides **1GB RAM** and **1 vCPU**, which is generally sufficient to run both our frontend and backend applications—requiring only around **604MB of RAM** for normal operation. However, the build process, triggered via our self-hosted GitHub Actions runner, demands more memory and CPU, leading to potential slowdowns or failures due to insufficient resources.  

The issue occurs during the **build process**, which takes about **3 minutes**. We are looking for a solution to **automatically increase the instance's resources** only during deployment (build time) and restore the instance to its normal size afterward. 

![Screenshot 2024-10-14 002438](https://github.com/user-attachments/assets/bed901d3-72a1-41e2-9e2d-39fa2ffdf9b4)

---

#### **Current Deployment Process**  
1. Code is pushed to the `master` branch on GitHub.
2. A **GitHub Action workflow** is triggered.
3. The workflow, defined in `.github/workflows/node.js.yml`, uses the self-hosted runner on the t2.micro instance to build and restart the app.

Here’s a summary of the relevant workflow configuration:

```yaml
name: Indigenous connect backend CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Copy environment files
      run: cp ~/env/backend/.env ./

    - name: Install dependencies with pnpm
      run: pnpm install

    - name: Build project
      run: pnpm run build 

    - name: Restart the app using pm2
      run: pm2 restart ic-backend
```

---

#### **Problem Statement**  
During the build step, additional resources (CPU + RAM) are required for the following tasks:  
- **Dependency installation**  
- **Project compilation and build**  

Since the t2.micro instance has limited capacity, the build process is prone to slowdowns and potentially fails due to lack of memory. Once the build is complete, the instance can comfortably handle the applications without any additional resources. **Increasing the instance size for just the build phase** will solve this issue without unnecessary costs or resource wastage.  

---

#### **Proposed Solution**  
We propose **temporarily scaling up resources during the build phase** and restoring the instance to its original state afterward. This approach ensures:
- Smooth operation during build without exhausting resources.
- Cost-effective management by only increasing resources for a few minutes.

**Possible Solutions:**
1. **AWS Auto Scaling**  
   - Implement auto-scaling rules based on load (CPU/memory utilization).
   - Automatically increase instance size to **t2.medium** during the build and revert to **t2.micro** when idle.

2. **AWS Lambda or Step Functions + EC2 API**  
   - Use Lambda or Step Functions to trigger an **instance resize** before the build process starts.
   - Resize back to **t2.micro** once the build completes successfully.

3. **EC2 Spot Instances**  
   - Use spot instances or a **temporary instance with higher capacity** for the build.
   - Deploy the build output to the production server after completion.

---

#### **Additional Context**  
- **Instance Type:** t2.micro  
- **Operating System:** Ubuntu  
- **Frontend + Backend Memory Usage:** ~604MB  
- **Build Time:** ~3 minutes  
- **Self-hosted Runner:** Yes  

---

#### **Impact**  
- This feature will improve **deployment reliability**.
- Avoid unnecessary resource usage, keeping operational costs low.
- Ensure a **smoother CI/CD pipeline** for future updates.

---

#### **Acceptance Criteria**  
- The instance should **auto-scale** or **resize** only for the build duration.
- After deployment, the instance should **revert to t2.micro** automatically.
- The entire process should run seamlessly without manual intervention.

---
